# Generated by Django 5.0.2 on 2026-07-10 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serhaefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heiti', models.CharField(max_length=100, unique=True, verbose_name='Heiti')),
                ('lysing', models.TextField(blank=True, verbose_name='Lýsing')),
                ('stofnad', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
            ],
            options={
                'verbose_name': 'Sérhæfi',
                'verbose_name_plural': 'Sérhæfi',
                'ordering': ['heiti'],
            },
        ),
        migrations.CreateModel(
            name='Notandi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('notandanafn', models.CharField(max_length=150, unique=True, verbose_name='Notandanafn')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Netfang')),
                ('fullt_nafn', models.CharField(max_length=255, verbose_name='Fullt nafn')),
                ('simanumer', models.CharField(blank=True, max_length=20, verbose_name='Símanúmer')),
                ('notendategund', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUB_ADMIN', 'Sub Admin (Yfirmaður)'), ('STARFSMADUR', 'Starfsmaður')], default='STARFSMADUR', max_length=20, verbose_name='Notendategund')),
                ('er_virkur', models.BooleanField(default=True, verbose_name='Er virkur')),
                ('er_starfsmadur', models.BooleanField(default=False, verbose_name='Er starfsmaður')),
                ('er_admin', models.BooleanField(default=False, verbose_name='Er stjórnandi')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Stofnaður')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Notandi',
                'verbose_name_plural': 'Notendur',
            },
        ),
        migrations.CreateModel(
            name='Starfsmadur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starfsmannanumer', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Starfsmannanúmer')),
                ('kennitala', models.CharField(max_length=11, unique=True, verbose_name='Kennitala')),
                ('heimilisfang', models.TextField(verbose_name='Heimilisfang')),
                ('simanumer', models.CharField(max_length=20, verbose_name='Símanúmer')),
                ('starfstitill', models.CharField(blank=True, max_length=255, verbose_name='Starfstitill')),
                ('active_directory_notandi', models.CharField(blank=True, max_length=150, verbose_name='Active Directory notandanafn')),
                ('qr_kodi', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR kóði')),
                ('aeskilegur_moettartimi', models.TimeField(blank=True, null=True, verbose_name='Æskilegur mætingartími')),
                ('aeskilegur_brottfararstimi', models.TimeField(blank=True, null=True, verbose_name='Æskilegur brottfarartími')),
                ('er_virkur', models.BooleanField(default=True, verbose_name='Er virkur')),
                ('rodun', models.PositiveIntegerField(default=0, verbose_name='Röðun')),
                ('stofnad', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('uppfaert', models.DateTimeField(auto_now=True, verbose_name='Uppfært')),
                ('notandi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starfsmadur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Notandi')),
                ('serhaefi', models.ManyToManyField(blank=True, to='starfsfolk.serhaefi', verbose_name='Sérhæfi')),
            ],
            options={
                'verbose_name': 'Starfsmaður',
                'verbose_name_plural': 'Starfsmenn',
                'ordering': ['rodun', '-stofnad'],
            },
        ),
        migrations.CreateModel(
            name='Maeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dagsetning', models.DateField(verbose_name='Dagsetning')),
                ('moettartimi', models.DateTimeField(blank=True, null=True, verbose_name='Mætingartími')),
                ('brottfararstimi', models.DateTimeField(blank=True, null=True, verbose_name='Brottfarartími')),
                ('status', models.CharField(choices=[('MAETTUR', 'Mættur'), ('FJARVERANDI', 'Fjarverandi'), ('VEIKUR', 'Veikur'), ('FRI', 'Frí'), ('UTKALL', 'Útkall')], default='FJARVERANDI', max_length=20, verbose_name='Staða')),
                ('athugasemdir', models.TextField(blank=True, verbose_name='Athugasemdir')),
                ('stofnad', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maetingar', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
            ],
            options={
                'verbose_name': 'Mæting',
                'verbose_name_plural': 'Mætingar',
                'ordering': ['-dagsetning'],
                'unique_together': {('starfsmadur', 'dagsetning')},
            },
        ),
        migrations.CreateModel(
            name='Fridagur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fra_dagsetning', models.DateField(verbose_name='Frá dagsetningu')),
                ('til_dagsetning', models.DateField(verbose_name='Til dagsetningar')),
                ('fridags_tegund', models.CharField(choices=[('ORLOF', 'Orlof'), ('VEIKINDI', 'Veikindi'), ('ANNAÐ', 'Annað')], max_length=20, verbose_name='Tegund')),
                ('lysing', models.TextField(blank=True, verbose_name='Lýsing')),
                ('stada', models.CharField(choices=[('OBIDINN', 'Óbíðinn'), ('SAMTHYKKTUR', 'Samþykktur'), ('SYNJAD', 'Synjað')], default='OBIDINN', max_length=20, verbose_name='Staða')),
                ('stofnad', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('uppfaert', models.DateTimeField(auto_now=True, verbose_name='Uppfært')),
                ('samthykkt_af', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samthykktir_fridagar', to=settings.AUTH_USER_MODEL, verbose_name='Samþykkt af')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridagar', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
            ],
            options={
                'verbose_name': 'Frídagur',
                'verbose_name_plural': 'Frídagar',
                'ordering': ['-fra_dagsetning'],
            },
        ),
        migrations.CreateModel(
            name='TimaklukkuLeidretting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_change', models.TextField(verbose_name='Óskuð leiðrétting')),
                ('reason', models.TextField(blank=True, verbose_name='Ástæða')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Staða')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yfirfarið')),
                ('manager_note', models.TextField(blank=True, verbose_name='Athugasemd stjórnanda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Uppfært')),
                ('maeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timaklukku_leidrettingar', to='starfsfolk.maeting', verbose_name='Mæting')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timaklukku_leidrettingar_yfirfarnar', to=settings.AUTH_USER_MODEL, verbose_name='Yfirfarið af')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timaklukku_leidrettingar', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
            ],
            options={
                'verbose_name': 'Tímaklukku leiðrétting',
                'verbose_name_plural': 'Tímaklukku leiðréttingar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimaklukkuTaeki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_label', models.CharField(blank=True, max_length=120, verbose_name='Tæki')),
                ('pairing_code_hash', models.CharField(blank=True, max_length=64, verbose_name='Pairing code hash')),
                ('status', models.CharField(choices=[('PAIRING', 'Pairing'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='PAIRING', max_length=20, verbose_name='Staða')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Síðast séð')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Afturkallað')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timaklukku_taeki', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
            ],
            options={
                'verbose_name': 'Tímaklukku tæki',
                'verbose_name_plural': 'Tímaklukku tæki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimaklukkuAtburdur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IN', 'Clock in'), ('OUT', 'Clock out'), ('BREAK_START', 'Break start'), ('BREAK_END', 'Break end'), ('CORRECTION_REQUESTED', 'Correction requested'), ('CORRECTION_APPROVED', 'Correction approved'), ('CORRECTION_REJECTED', 'Correction rejected'), ('DEVICE_CONNECTED', 'Device connected'), ('DEVICE_REVOKED', 'Device revoked')], max_length=30, verbose_name='Tegund')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tími')),
                ('source', models.CharField(choices=[('PHONE', 'Phone'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('API', 'API')], default='API', max_length=20, verbose_name='Uppruni')),
                ('note', models.TextField(blank=True, verbose_name='Athugasemd')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timaklukku_atburdir', to=settings.AUTH_USER_MODEL, verbose_name='Skráð af')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timaklukku_atburdir', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
                ('taeki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atburdir', to='starfsfolk.timaklukkutaeki', verbose_name='Tæki')),
            ],
            options={
                'verbose_name': 'Tímaklukku atburður',
                'verbose_name_plural': 'Tímaklukku atburðir',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vinnukostnadur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dagsetning', models.DateField(verbose_name='Dagsetning')),
                ('fjarhaed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fjárhæð')),
                ('kostnadar_tegund', models.CharField(choices=[('LAUN', 'Laun'), ('YFIRVINNUTIME', 'Yfirvinnustundir'), ('EFNISKOSTNADUR', 'Efniskostnaður'), ('ANNAD', 'Annað')], max_length=20, verbose_name='Tegund kostnaðar')),
                ('lysing', models.TextField(blank=True, verbose_name='Lýsing')),
                ('er_greitt', models.BooleanField(default=False, verbose_name='Er greitt')),
                ('stofnad', models.DateTimeField(auto_now_add=True, verbose_name='Stofnað')),
                ('starfsmadur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinnukostnadur', to='starfsfolk.starfsmadur', verbose_name='Starfsmaður')),
            ],
            options={
                'verbose_name': 'Vinnukostnaður',
                'verbose_name_plural': 'Vinnukostnaður',
                'ordering': ['-dagsetning'],
            },
        ),
    ]
